name: 生成 Vuepress 网站并部署

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 缓存的使用，还看不明白暂时去掉：https://github.com/marketplace/actions/cache
      # 恢复缓存
      - name: Restore Yarn dependencies from cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          # 备选 key
          restore-keys: ${{ runner.os }}-yarn-

      # https://github.com/marketplace/actions/setup-node-js-environment
      # 设置 nodejs 版本为 14.x，太高会运行出错
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: yarn run docs:build
        run: yarn install && yarn run docs:build

      # 保存缓存
      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      # https://github.com/marketplace/actions/github-pages-action
      # 部署
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/.vuepress/dist
